module.exports = {
  jobs: {
    "Truck Driver": {
      skills: [
        "Over 25 years old",
        "Driver license",
        "Clean driving record",
        "Flexible availability",
        "Heavy Rigid License",
        "Presentable",
        "Punctual",
        "Friendly",
        "\"Can Do\" attitude",
        "Excellent Presentation",
      ],
      benefits: [
        "401k",
        "Medical Insurance",
        "Dental Insurance",
        "Day shift",
        "Long Term Care Insurance",
        "Paid Sick Leave",
        "Paid Military Leave",
        "Paid holidays",
      ],
    },
    "Software Engineer - Computers & IT": {
      skills: [
        "Over 25 years old",
        "Driver license",
        "Clean driving record",
        "Flexible availability",
        "Heavy Rigid License",
        "Presentable",
        "Punctual",
        "Friendly",
        "\"Can Do\" attitude",
        "Excellent Presentation",
      ],
      benefits: [
        "401k",
        "Medical Insurance",
        "Dental Insurance",
        "Day shift",
        "Long Term Care Insurance",
        "Paid Sick Leave",
        "Paid Military Leave",
        "Paid holidays",
      ],
    },
    "Rail Engineer - Transport": {
      skills: [
        "Over 25 years old",
        "Driver license",
        "Clean driving record",
        "Flexible availability",
        "Heavy Rigid License",
        "Presentable",
        "Punctual",
        "Friendly",
        "\"Can Do\" attitude",
        "Excellent Presentation",
      ],
      benefits: [
        "401k",
        "Medical Insurance",
        "Dental Insurance",
        "Day shift",
        "Long Term Care Insurance",
        "Paid Sick Leave",
        "Paid Military Leave",
        "Paid holidays",
      ],
    },
    "Civil Engineer - Construction": {
      skills: [
        "Over 25 years old",
        "Driver license",
        "Clean driving record",
        "Flexible availability",
        "Heavy Rigid License",
        "Presentable",
        "Punctual",
        "Friendly",
        "\"Can Do\" attitude",
        "Excellent Presentation",
      ],
      benefits: [
        "401k",
        "Medical Insurance",
        "Dental Insurance",
        "Day shift",
        "Long Term Care Insurance",
        "Paid Sick Leave",
        "Paid Military Leave",
        "Paid holidays",
      ],
    },
  },
  locations: [
    "Ann Arbor, Michigan",
    "Austin, Texas",
    "Sydney, Australia",
    "Warsaw, Poland",
  ],
  spins: {
    "Over 25 years old": "Must be {older than|over} 25 years old.",
    "Driver license": "Must have a {valid|current} drivers license",
    "Clean driving record": "Must have a clean driving record",
    "Flexible availability": "Flexible availibiliy",
    "Heavy Rigid License": "Heavy Rigid License",
    "Presentable": "Presentable",
    "Punctual": "Punctual",
    "Friendly": "Frindly",
    "\"Can Do\" attitude": "\"Can Do\" attitude",
    "Excellent Presentation": "Excellent Presentation",
    "401k": "401k",
    "Medical Insurance": "Medical Insurance",
    "Dental Insurance": "Dental Insurance",
    "Day shift": "Day shift",
    "Long Term Care Insurance": "Long Term Care Insurance",
    "Paid Sick Leave": "Paid Sick Leave",
    "Paid Military Leave": "Paid Military Leave",
    "Paid holidays": "Paid holidays",
  },
}
