module.exports = {
  jobs: {
    "Truck Driver": {
      skills: [
        "Over 25 years old",
        "Driver license",
        "Clean driving record",
        "Flexible availability",
        "Heavy Rigid License",
        "Presentable",
        "Punctual",
        "Friendly",
        "\"Can Do\" attitude",
        "Excellent Presentation",
      ],
      benefits: [
        "401k",
        "Medical Insurance",
        "Dental Insurance",
        "Day shift",
        "Long Term Care Insurance",
        "Paid Sick Leave",
        "Paid Military Leave",
        "Paid holidays",
      ],
    },
    "Front-End Engineer": {
      skills: [
        "\"Can Do\" attitude",
        "Excellent Presentation",
        "JavaScript",
        "React.js",
        "HTML",
        "CSS",
        "CSS preprocessors",
        "Redux",
        "Angular.js",
        "Ember.js",
      ],
      benefits: [
        "401k",
        "Medical Insurance",
        "Dental Insurance",
        "Paid holidays",
        "Unlimited Vacation",
        "Work from home",
        "Ping-pong table",
        "Health and Wellness stipend",
        "Yearly bonus",
        "Open office",
        "Equity",
        "ESPP",
      ],
    }
  },
  locations: [
    "Ann Arbor, Michigan",
    "Austin, Texas",
    "Sydney, Australia",
    "Warsaw, Poland",
  ],
  spins: {
    "Over 25 years old": "Must be {older than|over} 25 years old.",
    "Driver license": "Must have a {valid|current} drivers license",
    "Clean driving record": "Must have a clean driving record",
    "Flexible availability": "Flexible availibiliy",
    "Heavy Rigid License": "Heavy Rigid License",
    "Presentable": "Presentable",
    "Punctual": "Punctual",
    "Friendly": "Frindly",
    "\"Can Do\" attitude": "\"Can Do\" attitude",
    "Excellent Presentation": "Excellent Presentation",
    "401k": "401k",
    "Medical Insurance": "Medical Insurance",
    "Dental Insurance": "Dental Insurance",
    "Day shift": "Day shift",
    "Long Term Care Insurance": "Long Term Care Insurance",
    "Paid Sick Leave": "Paid Sick Leave",
    "Paid Military Leave": "Paid Military Leave",
    "Paid holidays": "Paid holidays",
  },
  skills: [
    "Over 25 years old",
    "Driver license",
    "Clean driving record",
    "Flexible availability",
    "Heavy Rigid License",
    "Presentable",
    "Punctual",
    "Friendly",
    "\"Can Do\" attitude",
    "Excellent Presentation",
    "JavaScript",
    "ClojureScript",
    "React.js",
    "Om.cljs",
    "Haskell",
    "Ruby",
    "Go",
    "HTML",
    "CSS",
    "CSS preprocessors",
    "Redux",
    "Angular.js",
    "Ember.js",
  ],
  benefits: [
    "401k",
    "Medical Insurance",
    "Dental Insurance",
    "Day shift",
    "Long Term Care Insurance",
    "Paid Sick Leave",
    "Paid Military Leave",
    "Paid holidays",
    "Unlimited Vacation",
    "Work from home",
    "Ping-pong table",
    "Health and Wellness stipend",
    "Yearly bonus",
    "Open office",
    "Equity",
    "ESPP",
  ],
}
